import './globals.css';
import type { Metadata } from 'next';

import { inter } from '@/lib/fonts';
import { cn } from '@/lib/utils';

import { Providers } from './providers';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Next.js Template',
};

export default function RootLayout({ children }: Readonly<LayoutProps<'/'>>) {
  return (
    <html
      lang="en"
      className={cn('antialiased', 'font-sans', inter.variable)}
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
