export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  VALIDATION_FAILED: 'VALIDATION_FAILED',

  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  CONFLICT: 'CONFLICT',

  DATABASE_ERROR: 'DATABASE_ERROR',

  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;
